pull_request_rules:

- name: Automatically approve bot PRs
  conditions: &base_merge_conditions
  - status-success=shellcheck
  - author=horothesun-renovate[bot]
  actions:
    review:
      type: APPROVE

- name: Automatically merge bot PRs
  conditions:
  - and: *base_merge_conditions
  - and:
    - "#approved-reviews-by>=1"
  actions:
    merge:
      method: squash
